name: Node CI

on:
  - push

env:
  CI: true

jobs: 
  build: 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - run: make install
      - run: make lint
      - run: make test
