name: Node CI

on:
  - push

env:
  CI: true

jobs: 
  build: 
    runs-on: ubuntu-latest

    strategy:
      node-version: [18.x]

    steps:
      - run: make install
      - run: make lint
      - run: make test
